use std::fs;
use std::io::Write;
use std::path::Path;

use surmount_deploy_host::{
    assert_safe_token, is_path_under_root, is_public_product_path, realpath_m,
};

use crate::error::ToolError;
use crate::inventory::{InventoryOpts, run_inventory};

const BASE_FRAG: &str = r#"# PRIVATE host-local cutover fragments (generated by surmount-host-cutover).
# Do NOT commit this file to the public Surmount Server tree.
# Wire into the host evaluation via your private host-local import path only.
# Public sample host (hosts/mail-vps) stays enable=false for Vaultwarden and
# ACME default-off. See docs/OPS.md, docs/deploy-host-local.md, docs/SECRETS.md.
#
# Replace example.test / ops@example.test with operator values on the host.
# Paths are conventional; align with installed secrets-install destinations.
{ config, lib, ... }:
{
  # --- HTTPS PEMs (static host PEMs; durable H-PEM default) ---
  # surmount.managementUi = {
  #   listenMode = "https";
  #   tlsCertPath = "/var/lib/surmount/secrets/tls/cert.pem";
  #   tlsKeyPath = "/var/lib/surmount/secrets/tls/key.pem";
  #   redirectHttpToHttps = true;
  # };

  # --- In-process ACME staging + external-hook (optional alternate to static PEMs) ---
  # surmount.managementUi = {
  #   listenMode = "https";
  #   tlsCertPath = "/var/lib/surmount/secrets/tls/cert.pem";
  #   tlsKeyPath = "/var/lib/surmount/secrets/tls/key.pem";
  #   acme = {
  #     enable = true;
  #     directory = "https://acme-staging-v02.api.letsencrypt.org/directory";
  #     email = "ops@example.test";
  #     domains = [ "services.example.test" ];
  #     accountCredentialsPath = "/var/lib/surmount/secrets/acme/account.json";
  #     challenge = "dns-01";
  #     dnsProvider = "external-hook";
  #     dnsHookPath = "/run/surmount/acme-dns-hook";
  #   };
  # };
  # Production DNS-01 hook talks to operator-owned DNS (not the lab sample).
  # Lab sample: script/acme-dns-hook-lab.sh (temp zone file only).

  # --- requireDeployMaterial (B2 / O4; enable only after paths stable) ---
  # surmount.requireDeployMaterial = true;

  # --- restic include for Vaultwarden data (when VW live) ---
  # surmount.backups = {
  #   enable = true;
  #   paths = [ /var/lib/vaultwarden ];
  # };
}
"#;

const VW_FRAG: &str = r#"# PRIVATE host-local S7b Vaultwarden enable fragment (surmount-host-cutover).
# Do NOT commit to public hosts/. Sample public host stays enable=false.
# Install ADMIN_TOKEN EnvironmentFile first (kind vaultwarden-admin):
#   /var/lib/surmount/secrets/vaultwarden/admin.env  (ADMIN_TOKEN=...; mode 0600)
# S7a offline module is already in tree; this fragment only enables on host.
{ config, lib, ... }:
{
  surmount.vaultwarden = {
    enable = true;
    adminTokenEnvFile = "/var/lib/surmount/secrets/vaultwarden/admin.env";
    # domain = "https://vault.example.test"; # optional public URL when exposed
  };
  # Optional console link (loopback default is honest for SSH tunnel):
  # surmount.managementUi.vaultwardenUrl = "http://127.0.0.1:8222";
}
"#;

pub fn emit_fragments(
    dest: &Path,
    repo_root: &Path,
    with_vw: bool,
    acme_path: bool,
    dns_hook: &str,
    acme_account: &str,
    inv: Option<&InventoryOpts>,
) -> Result<(), ToolError> {
    if dest.as_os_str().is_empty() {
        return Err(ToolError::fail(
            "emit-fragments requires a destination directory",
        ));
    }
    if is_path_under_root(repo_root, &realpath_m(dest)) {
        return Err(ToolError::fail(format!(
            "refuse: fragment destination under public git work tree ({}). Use a private host-local directory outside the repo. See docs/deploy-host-local.md",
            dest.display()
        )));
    }
    if is_public_product_path(dest, repo_root) {
        return Err(ToolError::fail(format!(
            "refuse: will not write cutover fragments into public product path ({}). Use a private host-local directory outside hosts/ and secrets/. See docs/deploy-host-local.md",
            dest.display()
        )));
    }
    assert_safe_token("dns-hook-path-hint", dns_hook)?;
    assert_safe_token("acme-account-path", acme_account)?;
    fs::create_dir_all(dest)?;
    let out = dest.join("surmount-cutover-fragments.nix");
    let vw_out = dest.join("surmount-vaultwarden-enable.nix");
    let mut body = BASE_FRAG.to_string();
    if acme_path {
        body.push_str("\n# host-cutover note: generated with --acme-path\n");
        body.push_str(
            "# Prefer enabling the ACME block above after the DNS-01 hook is in place.\n",
        );
        body.push_str(&format!("# dnsHookPath hint: {dns_hook}\n"));
        body.push_str(&format!("# accountCredentialsPath hint: {acme_account}\n"));
    }
    fs::write(&out, body)?;
    eprintln!(
        "host-cutover: wrote private fragment file {} (commented; no live secrets)",
        out.display()
    );

    if with_vw {
        let Some(inv) = inv else {
            return Err(ToolError::fail(
                "VW enable fragment requires --staging (material gate)",
            ));
        };
        if run_inventory(inv, repo_root).is_err() {
            let _ = fs::remove_file(&vw_out);
            return Err(ToolError::fail(
                "refuse: VW enable fragment requires complete inventory under --with-vaultwarden (vaultwarden-admin material). No enable file written.",
            ));
        }
        fs::write(&vw_out, VW_FRAG)?;
        eprintln!(
            "host-cutover: wrote S7b Vaultwarden enable fragment {} (private host-local only; material gate passed)",
            vw_out.display()
        );
    } else if vw_out.exists() || vw_out.symlink_metadata().is_ok() {
        let _ = fs::remove_file(&vw_out);
        eprintln!(
            "host-cutover: removed stale VW enable fragment (profile off): {}",
            vw_out.display()
        );
    }
    let _ = std::io::stderr().flush();
    Ok(())
}
