//! Render host-local-acme.nix from a private host profile (no secrets).

use std::ffi::OsString;
use std::fs;
use std::path::{Path, PathBuf};

use crate::cred::die;

const SAMPLE_COMMENT: &str = "PRIVATE host-local ACME fragment (generated by surmount-render-host-profile-acme).";

pub const USAGE: &str = r#"Usage:
  surmount-render-host-profile-acme --profile PATH --out DIR [--force]
  surmount-render-host-profile-acme --profile PATH --stdout
  surmount-render-host-profile-acme --help

Render a private host profile into host-local-acme.nix (ACME + public listen).
No secrets: domains, email, directory URL, conventional paths, listen knobs.
"#;

#[derive(Default)]
struct Profile {
    host_id: String,
    email: String,
    directory: String,
    dns_provider: String,
    dns_hook: String,
    account: String,
    tls_cert: String,
    tls_key: String,
    listen_address: String,
    listen_port: String,
    redirect_http: String,
    http_redirect_listen: String,
    domains: Vec<String>,
}

pub fn run<I, S>(args: I) -> u8
where
    I: IntoIterator<Item = S>,
    S: Into<OsString>,
{
    match run_inner(args) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

fn run_inner<I, S>(args: I) -> anyhow::Result<u8>
where
    I: IntoIterator<Item = S>,
    S: Into<OsString>,
{
    let mut args: Vec<String> = args
        .into_iter()
        .map(|s| s.into().to_string_lossy().into_owned())
        .collect();
    if !args.is_empty() {
        args.remove(0);
    }
    let mut profile_path = None;
    let mut out_dir = None;
    let mut stdout_only = false;
    let mut force = false;
    let mut dir_override = None;
    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--help" | "-h" => {
                print!("{USAGE}");
                return Ok(0);
            }
            "--profile" => {
                i += 1;
                profile_path = Some(args.get(i).cloned().ok_or_else(|| die("render-host-profile-acme", "--profile PATH"))?);
            }
            "--out" => {
                i += 1;
                out_dir = Some(args.get(i).cloned().ok_or_else(|| die("render-host-profile-acme", "--out DIR"))?);
            }
            "--stdout" => stdout_only = true,
            "--force" => force = true,
            "--directory" | "--set-directory" => {
                i += 1;
                dir_override = Some(args.get(i).cloned().ok_or_else(|| die("render-host-profile-acme", "--directory VAL"))?);
            }
            other => return Err(die("render-host-profile-acme", format!("unknown argument: {other}"))),
        }
        i += 1;
    }
    let profile_path = profile_path.ok_or_else(|| die("render-host-profile-acme", "--profile PATH required"))?;
    let mut p = parse_profile(Path::new(&profile_path))?;
    if p.email.is_empty() {
        return Err(die("render-host-profile-acme", "acme_email required"));
    }
    if p.domains.is_empty() {
        return Err(die("render-host-profile-acme", "acme_domains required"));
    }
    if p.directory.is_empty() {
        p.directory = "https://acme-staging-v02.api.letsencrypt.org/directory".into();
    }
    if let Some(d) = dir_override {
        p.directory = match d.as_str() {
            "production" => "https://acme-v02.api.letsencrypt.org/directory".into(),
            "staging" => "https://acme-staging-v02.api.letsencrypt.org/directory".into(),
            u if u.starts_with("https://") => u,
            other => return Err(die("render-host-profile-acme", format!("unknown --directory {other}"))),
        };
    }
    if p.dns_provider.is_empty() {
        p.dns_provider = "external-hook".into();
    }
    if p.dns_hook.is_empty() {
        p.dns_hook = "/run/surmount/acme-dns-hook".into();
    }
    if p.account.is_empty() {
        p.account = "/var/lib/surmount/secrets/acme/account.json".into();
    }
    if p.tls_cert.is_empty() {
        p.tls_cert = "/var/lib/surmount/secrets/tls/cert.pem".into();
    }
    if p.tls_key.is_empty() {
        p.tls_key = "/var/lib/surmount/secrets/tls/key.pem".into();
    }
    if p.listen_address.is_empty() {
        p.listen_address = "0.0.0.0".into();
    }
    if p.listen_port.is_empty() {
        p.listen_port = "443".into();
    }
    if p.redirect_http.is_empty() {
        p.redirect_http = "true".into();
    }
    if p.http_redirect_listen.is_empty() {
        p.http_redirect_listen = "0.0.0.0:80".into();
    }
    let body = render_fragment(&p, &profile_path);
    if stdout_only {
        print!("{body}");
        return Ok(0);
    }
    let out_dir = out_dir.ok_or_else(|| die("render-host-profile-acme", "--out DIR or --stdout required"))?;
    refuse_public_tree(Path::new(&out_dir))?;
    fs::create_dir_all(&out_dir).map_err(|e| die("render-host-profile-acme", format!("out dir: {e}")))?;
    let dest = PathBuf::from(&out_dir).join("host-local-acme.nix");
    if dest.exists() && !force {
        return Err(die(
            "render-host-profile-acme",
            format!("exists (pass --force to overwrite): {}", dest.display()),
        ));
    }
    fs::write(&dest, body).map_err(|e| die("render-host-profile-acme", format!("write: {e}")))?;
    Ok(0)
}

fn refuse_public_tree(out: &Path) -> anyhow::Result<()> {
    for c in out.components() {
        if let std::path::Component::Normal(n) = c {
            if n == "hosts" || n == "secrets" || n == "docs" {
                return Err(die(
                    "render-host-profile-acme",
                    "refuse writing under the public git work tree (hosts/, secrets/, docs/)",
                ));
            }
        }
    }
    Ok(())
}

fn unquote(v: &str) -> String {
    let v = v.trim();
    if v.len() >= 2 && ((v.starts_with('"') && v.ends_with('"')) || (v.starts_with('\'') && v.ends_with('\'')))
    {
        v[1..v.len() - 1].to_string()
    } else {
        v.to_string()
    }
}

fn parse_profile(path: &Path) -> anyhow::Result<Profile> {
    let meta = fs::symlink_metadata(path)
        .map_err(|_| die("render-host-profile-acme", format!("profile missing: {}", path.display())))?;
    if meta.file_type().is_symlink() {
        return Err(die(
            "render-host-profile-acme",
            format!("profile must be a regular file (symlink refused): {}", path.display()),
        ));
    }
    let text = fs::read_to_string(path)
        .map_err(|_| die("render-host-profile-acme", format!("profile unreadable: {}", path.display())))?;
    let mut p = Profile::default();
    let mut in_domains = false;
    for raw in text.lines() {
        let line = raw.trim().trim_end_matches('\r');
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if in_domains {
            if line == "]" {
                in_domains = false;
                continue;
            }
            let val = unquote(line.trim_end_matches(',').trim());
            if !val.is_empty() {
                p.domains.push(val);
            }
            continue;
        }
        let Some((key, val)) = line.split_once('=') else {
            return Err(die(
                "render-host-profile-acme",
                format!("profile line must be key = value (file={}): {line}", path.display()),
            ));
        };
        let key = key.trim();
        let val = val.trim();
        match key {
            "acme_domains" => {
                if val == "[" {
                    in_domains = true;
                } else if val.starts_with('[') && val.ends_with(']') {
                    let inner = &val[1..val.len() - 1];
                    for part in inner.split(',') {
                        let part = unquote(part);
                        if !part.is_empty() {
                            p.domains.push(part);
                        }
                    }
                } else {
                    for part in unquote(val).split(',') {
                        let part = part.trim();
                        if !part.is_empty() {
                            p.domains.push(part.to_string());
                        }
                    }
                }
            }
            "acme_email" => p.email = unquote(val),
            "acme_directory" => p.directory = unquote(val),
            "host_id" => p.host_id = unquote(val),
            "dns_provider" => p.dns_provider = unquote(val),
            "dns_hook_path" => p.dns_hook = unquote(val),
            "account_credentials_path" => p.account = unquote(val),
            "tls_cert_path" => p.tls_cert = unquote(val),
            "tls_key_path" => p.tls_key = unquote(val),
            "listen_address" => p.listen_address = unquote(val),
            "listen_port" => p.listen_port = unquote(val),
            "redirect_http_to_https" => p.redirect_http = unquote(val),
            "http_redirect_listen" => p.http_redirect_listen = unquote(val),
            _ => {}
        }
    }
    Ok(p)
}

fn render_fragment(p: &Profile, profile_path: &str) -> String {
    let domains = p
        .domains
        .iter()
        .map(|d| format!("\"{d}\""))
        .collect::<Vec<_>>()
        .join(" ");
    let host = if p.host_id.is_empty() {
        String::new()
    } else {
        format!("# host_id: {}\n", p.host_id)
    };
    format!(
        r#"# {SAMPLE_COMMENT}
# Do NOT commit this file to the public Surmount Server tree.
# Wire via flake host-local known name host-local-acme.nix, or import from default.nix.
# Profile source (path only): {profile_path}
{host}# Non-secrets only: domains, email, ACME directory, public listen, conventional paths.
# Namecheap API / PEMs / account JSON are Domain B files (never this profile).
{{ config, lib, ... }}:
{{
  surmount.managementUi = {{
    listenMode = "https";
    listenAddress = "{la}";
    port = {lp};
    redirectHttpToHttps = {rh};
    httpRedirectListen = "{hrl}";
    tlsCertPath = "{tc}";
    tlsKeyPath = "{tk}";
    acme = {{
      enable = true;
      directory = "{dir}";
      email = "{email}";
      domains = [ {domains} ];
      accountCredentialsPath = "{acc}";
      challenge = "dns-01";
      dnsProvider = "{dp}";
      dnsHookPath = "{dh}";
    }};
  }};
}}
"#,
        SAMPLE_COMMENT = SAMPLE_COMMENT,
        profile_path = profile_path,
        host = host,
        la = p.listen_address,
        lp = p.listen_port,
        rh = p.redirect_http,
        hrl = p.http_redirect_listen,
        tc = p.tls_cert,
        tk = p.tls_key,
        dir = p.directory,
        email = p.email,
        domains = domains,
        acc = p.account,
        dp = p.dns_provider,
        dh = p.dns_hook,
    )
}
