# PRIVATE host-local ACME fragment (generated by nix run .#surmount-render-host-profile-acme).
# Do NOT commit this file to the public Surmount Server tree.
# Wire via flake host-local known name host-local-acme.nix, or import from default.nix.
# Profile source (path only): <profile-path>
# host_id: mail-lab
# Non-secrets only: domains, email, ACME directory, public listen, conventional paths.
# Namecheap API / PEMs / account JSON are Domain B files (never this profile).
{ config, lib, ... }:
{
  surmount.managementUi = {
    listenMode = "https";
    listenAddress = "0.0.0.0";
    port = 443;
    redirectHttpToHttps = true;
    httpRedirectListen = "0.0.0.0:80";
    tlsCertPath = "/var/lib/surmount/secrets/tls/cert.pem";
    tlsKeyPath = "/var/lib/surmount/secrets/tls/key.pem";
    acme = {
      enable = true;
      directory = "https://acme-staging-v02.api.letsencrypt.org/directory";
      email = "ops@example.invalid";
      domains = [ "services.example.invalid" "mail.example.invalid" "example.invalid" "www.example.invalid" ];
      accountCredentialsPath = "/var/lib/surmount/secrets/acme/account.json";
      challenge = "dns-01";
      dnsProvider = "external-hook";
      dnsHookPath = "/run/surmount/acme-dns-hook";
    };
  };
}
